### ISSUE TITLE
How to format font

### ISSUE THREAD

**Issue by Tim-VL** [sschreier/SschreierBadgeNavigationProductDetailPage#1]
Hi,

Is there a way to format the font of the badges?  It's now linked to the body font setting, and I would like to set a 'own' font size for the badges.

Thanks,
Tim

**Comment by sschreier** [comment]
Hi Tim,

of course - as part of your own theme app. That's where the styling of shop components, especially when you want to set own fonts, always belongs. Each badge has own css classes as you can see here: https://github.com/sschreier/SschreierBadgeNavigationProductDetailPage/blob/master/src/Resources/views/storefront/component/product/card/badge-custom.html.twig#L2 . Above this you can easily set a other font.

Best regards,

Sebastian

**Comment by Tim-VL** [comment]
Hi Sebastian,

Thank, will have an look at that.

Regrads,
Tim
