### ISSUE TITLE
Badge showing double on listing

### ISSUE THREAD

**Issue by Tim-VL** [sschreier/SschreierBadgeNavigationProductDetailPage#5]
Badges are showing double on the listing, not on the PDP.

![afbeelding](https://user-images.githubusercontent.com/75847795/211537318-7540b520-0a20-40a3-bf17-fe3c968c8559.png)

Any idea how to fix this?

**Comment by Tim-VL** [comment]
Fixed by the theme designer.

**Comment by sschreier** [comment]
Hello Tim,

the error can only be caused by the theme you are using.

Best regards

Sebastian
